In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

from config import g_key

# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kapaa,US,2021-04-18 16:01:18,22.0752,-159.3190,69.80,73,90,6.91
1,1,Henties Bay,NaN,2021-04-18 16:01:18,-22.1160,14.2845,85.24,36,96,14.72
2,2,Tiksi,RU,2021-04-18 16:01:19,71.6872,128.8694,6.48,89,100,12.55
3,3,Airai,TL,2021-04-18 16:01:19,-8.9266,125.4092,56.93,81,75,2.71
4,4,Hervey Bay,AU,2021-04-18 16:01:19,-25.2986,152.8535,64.00,85,0,4.00

In [2]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [4]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [5]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [10]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Henties Bay,NaN,2021-04-18 16:01:18,-22.1160,14.2845,85.24,36,96,14.72
5,5,Rikitea,PF,2021-04-18 16:01:20,-23.1203,-134.9692,76.75,74,1,6.62
9,9,Bredasdorp,ZA,2021-04-18 16:01:21,-34.5322,20.0403,80.60,17,8,12.66
10,10,Puerto Ayora,EC,2021-04-18 16:01:22,-0.7393,-90.3518,78.80,89,75,9.22
12,12,Garowe,SO,2021-04-18 16:01:22,8.4054,48.4845,84.38,43,7,21.97
15,15,Conakry,GN,2021-04-18 16:01:23,9.5380,-13.6773,87.80,62,20,13.80
17,17,Cape Town,ZA,2021-04-18 15:58:30,-33.9258,18.4232,80.60,26,0,10.36
19,19,Marrakesh,MA,2021-04-18 16:00:56,31.6315,-8.0083,86.00,25,20,5.75
23,23,Bengkulu,ID,2021-04-18 16:01:25,-3.8004,102.2655,75.25,89,76,3.89
25,25,Souillac,MU,2021-04-18 16:01:25,-20.5167,57.5167,75.20,94,75,16.11

In [11]:
preferred_cities_df.count()

City_ID       162
City          162
Country       159
Date          162
Lat           162
Lng           162
Max Temp      162
Humidity      162
Cloudiness    162
Wind Speed    162
dtype: int64

In [12]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
1    Henties Bay     NaN     85.24 -22.1160   14.2845
5        Rikitea      PF     76.75 -23.1203 -134.9692
9     Bredasdorp      ZA     80.60 -34.5322   20.0403
10  Puerto Ayora      EC     78.80  -0.7393  -90.3518
12        Garowe      SO     84.38   8.4054   48.4845
15       Conakry      GN     87.80   9.5380  -13.6773
17     Cape Town      ZA     80.60 -33.9258   18.4232
19     Marrakesh      MA     86.00  31.6315   -8.0083
23      Bengkulu      ID     75.25  -3.8004  102.2655
25      Souillac      MU     75.20 -20.5167   57.5167

In [13]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [15]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
   # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

KeyboardInterrupt:

In [16]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Henties Bay,NaN,85.24,-22.1160,14.2845,Fishermans Guest House
5,Rikitea,PF,76.75,-23.1203,-134.9692,Pension Maro'i
9,Bredasdorp,ZA,80.60,-34.5322,20.0403,Bredasdorp Country Manor
10,Puerto Ayora,EC,78.80,-0.7393,-90.3518,Finch Bay Galapagos Hotel
12,Garowe,SO,84.38,8.4054,48.4845,Curubo Hotel
15,Conakry,GN,87.80,9.5380,-13.6773,Riviera Royal Hotel
17,Cape Town,ZA,80.60,-33.9258,18.4232,Southern Sun Waterfront Cape Town
19,Marrakesh,MA,86.00,31.6315,-8.0083,Novotel Marrakech Hivernage
23,Bengkulu,ID,75.25,-3.8004,102.2655,Grage Hotel Bengkulu
25,Souillac,MU,75.20,-20.5167,57.5167,Shanti Maurice Resort & Spa

In [17]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

NameError: name 'hotel_info' is not defined